/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wvvqgadnwhzumrvllcnq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2dnFnYWRud2h6dW1ydmxsY25xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyODk5MTMsImV4cCI6MjA3Nzg2NTkxM30.v4uQUj8P-ozholx2XaiIV3DYnqSrC57oZ19j6NfQCNs"
